const analyzerSamples = {
  human: `When I first joined the lab, I expected the work to be mostly technical. What surprised me was how much of the project depended on small conversations, messy drafts, and revisions that only made sense after a few failed attempts. The final result looked polished, but the process was full of hesitation and compromise.`,
  ai: `The rapid evolution of digital communication has created a landscape in which evaluating textual authenticity is increasingly important. By examining stylistic consistency, probabilistic regularity, and cohesion under perturbation, one can systematically estimate whether a passage is likely to have been generated by an automated language model.`,
  mixed: `The café was almost empty when I started writing, and for a while the room felt quiet enough to hear the espresso machine cooling down. Still, the argument in my paper kept turning into tidy, over-explained paragraphs, as if a machine had decided that every thought needed to sound complete and perfectly balanced.`
};

const gameCases = [
  {
    label: "human",
    text: "I kept the rejection email for three weeks before deleting it. Not because I thought I could change the result, but because the wording was so polished that it almost made me feel grateful for being turned down.",
    reason: "The phrasing is specific, emotionally awkward, and anchored in a concrete personal detail."
  },
  {
    label: "ai",
    text: "In modern academic environments, students increasingly benefit from adaptive learning systems that personalize content delivery, optimize feedback cycles, and support diverse instructional outcomes across disciplines.",
    reason: "The sentence is broad, polished, and packed with abstract nouns rather than lived detail."
  },
  {
    label: "human",
    text: "My notes from the meeting looked impressive until I read them the next morning and realized I had written 'fix model confidence vibes' three separate times with no explanation.",
    reason: "There is humor, mild inconsistency, and a distinctly human kind of shorthand."
  },
  {
    label: "ai",
    text: "The integration of multimodal forensic signals provides a robust framework for identifying synthetic content while maintaining scalability and interpretability in real-world deployment settings.",
    reason: "It sounds competent, but it is too generic and too optimized for sounding formal."
  }
];

const textInput = document.querySelector("#text-input");
const analyzeBtn = document.querySelector("#analyze-btn");
const shuffleBtn = document.querySelector("#shuffle-btn");
const sampleChips = document.querySelectorAll(".sample-chip");
const modeTabs = document.querySelectorAll(".mode-tab");
const inputModes = document.querySelectorAll(".input-mode");
const verdictTitle = document.querySelector("#verdict-title");
const scoreValue = document.querySelector("#score-value");
const scoreRing = document.querySelector("#score-ring");
const meterFill = document.querySelector("#meter-fill");
const confidenceValue = document.querySelector("#confidence-value");
const ratioValue = document.querySelector("#ratio-value");
const cueValue = document.querySelector("#cue-value");
const sentenceList = document.querySelector("#sentence-list");
const featureGrid = document.querySelector("#feature-grid");
const modelStatus = document.querySelector("#model-status");
const deviceStatus = document.querySelector("#device-status");
const demoModeStatus = document.querySelector("#demo-mode-status");

const guessText = document.querySelector("#guess-text");
const roundCounter = document.querySelector("#round-counter");
const gameScore = document.querySelector("#game-score");
const answerLabel = document.querySelector("#answer-label");
const answerReason = document.querySelector("#answer-reason");
const guessHuman = document.querySelector("#guess-human");
const guessAi = document.querySelector("#guess-ai");
const revealBtn = document.querySelector("#reveal-btn");
const nextBtn = document.querySelector("#next-btn");
const imageInput = document.querySelector("#image-input");
const audioInput = document.querySelector("#audio-input");
const videoInput = document.querySelector("#video-input");
const videoUrlInput = document.querySelector("#video-url-input");
const inspectVideoBtn = document.querySelector("#inspect-video-btn");
const imageStatus = document.querySelector("#image-status");
const audioStatus = document.querySelector("#audio-status");
const videoStatus = document.querySelector("#video-status");
const imageBox = document.querySelector("#image-box");
const audioBox = document.querySelector("#audio-box");
const videoBox = document.querySelector("#video-box");
const frameBox = document.querySelector("#frame-box");
const voiceBox = document.querySelector("#voice-box");
const subtitleBox = document.querySelector("#subtitle-box");

let score = 0;
let attempts = 0;
let currentCase = 0;
let currentMode = "text";

const modeModelMap = {
  text: "CSPF-Net",
  image: "EfficientNet-B7 + Dual Attention / Community Forensics (ViT-based)",
  audio: "Lightweight CNN on Log-Mel Spectrograms / SpecTTTra + CNN-XGBoost",
  video: "Frame + Audio + Subtitle Fusion"
};

const modeDeviceMap = {
  text: "CUDA Text Inference",
  image: "Frame GPU Inspection",
  audio: "Audio Pipeline Ready",
  video: "Frame + Audio + OCR Stack"
};

const modeDemoStatusMap = {
  text: "Live Text Analysis",
  image: "Image Intake Preview",
  audio: "Audio Intake Preview",
  video: "Link Decomposition Demo"
};

function splitSentences(text) {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function analyzeText(text) {
  const sentences = splitSentences(text);
  const wordCount = text.trim().split(/\s+/).filter(Boolean).length;
  const longWordRatio = text
    .split(/\s+/)
    .filter((word) => word.replace(/[^a-zA-Z]/g, "").length >= 8).length / Math.max(wordCount, 1);
  const punctuationDensity = (text.match(/[,:;()-]/g) || []).length / Math.max(wordCount, 1);
  const formalCueCount = (text.match(/\b(increasingly|robust|framework|systematic|deployment|optimize|landscape|furthermore)\b/gi) || []).length;
  const personalCueCount = (text.match(/\b(I|my|me|we|our|yesterday|morning|night)\b/gi) || []).length;

  let aiScore = 0.32;
  aiScore += longWordRatio * 0.85;
  aiScore += punctuationDensity * 1.1;
  aiScore += formalCueCount * 0.08;
  aiScore -= personalCueCount * 0.06;
  aiScore = clamp(aiScore, 0.06, 0.96);

  const sentenceScores = sentences.map((sentence, index) => {
    const base = aiScore + ((sentence.match(/\b(robust|systematic|increasingly|framework|scalability)\b/gi) || []).length * 0.09);
    const personalOffset = (sentence.match(/\b(I|my|me|we)\b/gi) || []).length * 0.08;
    return clamp(base - personalOffset + (index % 2 === 0 ? 0.02 : -0.01), 0.05, 0.98);
  });

  const suspiciousCount = sentenceScores.filter((score) => score >= 0.58).length;
  const confidence = clamp(0.56 + Math.abs(aiScore - 0.5) * 0.88, 0.51, 0.97);
  const verdict = aiScore >= 0.55 ? "Likely AI" : aiScore <= 0.4 ? "Likely Human" : "Borderline / Mixed";

  let cue = "Balanced stylistic signals";
  if (formalCueCount >= 2) cue = "Overly polished abstraction";
  if (personalCueCount >= 2) cue = "Concrete personal detail";
  if (suspiciousCount > sentences.length / 2) cue = "Sentence-level consistency spike";

  return {
    verdict,
    aiScore,
    confidence,
    suspiciousCount,
    sentenceScores,
    sentences,
    cue,
    features: [
      {
        name: "Style entropy",
        value: `${Math.round((1 - longWordRatio) * 100)}%`,
        detail: longWordRatio > 0.24 ? "Dense academic diction" : "More natural lexical spread"
      },
      {
        name: "Probabilistic regularity",
        value: `${Math.round(aiScore * 100)}%`,
        detail: aiScore > 0.55 ? "Higher LM-likeness" : "Less templated flow"
      },
      {
        name: "Cohesion stress test",
        value: `${Math.round((0.4 + punctuationDensity * 4) * 100)}%`,
        detail: punctuationDensity > 0.09 ? "Rigid sentence packing" : "Looser human rhythm"
      }
    ]
  };
}

function renderAnalysis(result) {
  const scorePercent = Math.round(result.aiScore * 100);
  verdictTitle.textContent = result.verdict;
  scoreValue.textContent = `${scorePercent}%`;
  confidenceValue.textContent = `${Math.round(result.confidence * 100)}%`;
  ratioValue.textContent = `${result.suspiciousCount} / ${result.sentences.length || 1}`;
  cueValue.textContent = result.cue;
  meterFill.style.width = `${scorePercent}%`;
  scoreRing.style.background = `conic-gradient(var(--bad) 0deg, var(--bad) ${scorePercent * 3.6}deg, rgba(255, 255, 255, 0.08) ${scorePercent * 3.6}deg)`;

  sentenceList.innerHTML = "";
  result.sentences.forEach((sentence, index) => {
    const score = result.sentenceScores[index];
    const item = document.createElement("article");
    item.className = "sentence-item";
    item.style.borderLeftColor = `hsl(${120 - score * 120} 90% 65%)`;
    item.style.background = `linear-gradient(90deg, rgba(255, 95, 109, ${score * 0.24}), rgba(255, 255, 255, 0.03))`;
    item.innerHTML = `
      <div class="sentence-meta">
        <span>Sentence ${index + 1}</span>
        <span>${Math.round(score * 100)}% AI-likely</span>
      </div>
      <div>${sentence}</div>
    `;
    sentenceList.appendChild(item);
  });

  featureGrid.innerHTML = "";
  result.features.forEach((feature) => {
    const box = document.createElement("article");
    box.className = "feature-box";
    box.innerHTML = `
      <span class="stat-label">${feature.name}</span>
      <strong>${feature.value}</strong>
      <p>${feature.detail}</p>
    `;
    featureGrid.appendChild(box);
  });
}

function setSample(sampleKey) {
  textInput.value = analyzerSamples[sampleKey];
  renderAnalysis(analyzeText(textInput.value));
}

function renderGameCase() {
  const item = gameCases[currentCase];
  guessText.textContent = item.text;
  roundCounter.textContent = `Case ${currentCase + 1} / ${gameCases.length}`;
  answerLabel.textContent = "Hidden";
  answerReason.textContent = "Ask the room to vote first, then reveal the explanation.";
}

function setMode(mode) {
  currentMode = mode;
  modelStatus.textContent = modeModelMap[mode] || "CSPF-Net";
  deviceStatus.textContent = modeDeviceMap[mode] || "Runtime Ready";
  demoModeStatus.textContent = modeDemoStatusMap[mode] || "Frontend Prototype";
  modeTabs.forEach((tab) => {
    tab.classList.toggle("active", tab.dataset.mode === mode);
  });
  inputModes.forEach((panel) => {
    panel.classList.toggle("active", panel.dataset.panel === mode);
  });
}

function updateModalityBox(box, label, detail) {
  box.classList.add("active");
  box.innerHTML = `
    <span class="stat-label">${label}</span>
    <strong>Loaded</strong>
    <p>${detail}</p>
  `;
}

function updateDecompositionBox(box, label, title, detail) {
  box.classList.add("active");
  box.innerHTML = `
    <span class="stat-label">${label}</span>
    <strong>${title}</strong>
    <p>${detail}</p>
  `;
}

function inspectVideoSource(sourceLabel) {
  videoStatus.textContent = `${sourceLabel} accepted. The demo will decompose the video into image frames, audio, and subtitles for separate forensic checks.`;
  updateModalityBox(videoBox, "Video", `${sourceLabel} mapped to a multimodal decomposition workflow.`);
  updateDecompositionBox(frameBox, "Frame Track", "Queued", "Sample keyframes would be extracted and sent to the image branch for visual artifact checks.");
  updateDecompositionBox(voiceBox, "Audio Track", "Queued", "The soundtrack would be separated for speech analysis and synthetic-voice cues.");
  updateDecompositionBox(subtitleBox, "Subtitle Track", "Queued", "OCR or ASR output would be routed into the text detector for language-based forensics.");
}

function revealCase(showAnswerOnly = false) {
  const item = gameCases[currentCase];
  answerLabel.textContent = item.label === "ai" ? "AI-generated" : "Human-written";
  answerReason.textContent = item.reason;
  if (!showAnswerOnly) {
    gameScore.textContent = `${score} / ${attempts}`;
  }
}

guessHuman.addEventListener("click", () => {
  attempts += 1;
  if (gameCases[currentCase].label === "human") score += 1;
  revealCase();
});

guessAi.addEventListener("click", () => {
  attempts += 1;
  if (gameCases[currentCase].label === "ai") score += 1;
  revealCase();
});

revealBtn.addEventListener("click", () => revealCase(true));
nextBtn.addEventListener("click", () => {
  currentCase = (currentCase + 1) % gameCases.length;
  renderGameCase();
});

analyzeBtn.addEventListener("click", () => {
  renderAnalysis(analyzeText(textInput.value));
});

shuffleBtn.addEventListener("click", () => {
  const keys = Object.keys(analyzerSamples);
  const randomKey = keys[Math.floor(Math.random() * keys.length)];
  setSample(randomKey);
});

sampleChips.forEach((chip) => {
  chip.addEventListener("click", () => setSample(chip.dataset.sample));
});

modeTabs.forEach((tab) => {
  tab.addEventListener("click", () => setMode(tab.dataset.mode));
});

imageInput.addEventListener("change", () => {
  const file = imageInput.files?.[0];
  if (!file) return;
  imageStatus.textContent = `Loaded ${file.name}. Frontend intake is ready; image forensics backend is not connected yet.`;
  updateModalityBox(imageBox, "Image", `${file.name} accepted into the demo UI.`);
});

audioInput.addEventListener("change", () => {
  const file = audioInput.files?.[0];
  if (!file) return;
  audioStatus.textContent = `Loaded ${file.name}. Frontend intake is ready; audio detection backend is not connected yet.`;
  updateModalityBox(audioBox, "Audio", `${file.name} accepted into the demo UI.`);
});

videoInput.addEventListener("change", () => {
  const file = videoInput.files?.[0];
  if (!file) return;
  inspectVideoSource(file.name);
});

inspectVideoBtn.addEventListener("click", () => {
  const url = videoUrlInput.value.trim();
  if (!url) {
    videoStatus.textContent = "Paste a Xiaohongshu video URL first. The demo accepts a link and then shows the decomposition pipeline.";
    return;
  }
  inspectVideoSource(url);
});

setSample("human");
renderGameCase();
setMode(currentMode);
